// src/main.js
import { createApp } from 'vue'
import { createPinia } from 'pinia'
import Toast from 'vue-toastification'
import 'vue-toastification/dist/index.css'
import VueLazyLoad from 'vue3-lazyload'

// FontAwesome imports
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faSearch,
  faShoppingCart,
  faUser,
  faBars,
  faTimes,
  faHome,
  faShop,
  faInfoCircle,
  faBlog,
  faPhone,
  faBriefcase,
  faShieldAlt,
  faUndo,
  faHeadset,
  faTruck,
  faDashboard,
  faBox,
  faMapMarkerAlt,
  faSignOut,
  faEye,
  faBolt,
  faHeart,
  faTachometerAlt,
  faSignOutAlt,
  faEyeSlash,
  faPlus,
  faMinus,
  faTrash,
  faCheck,
  faArrowRight,
  faArrowLeft,
  faSpinner,
  faStar,
  faFilter,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faEnvelope,
  faLock,
  faUserCircle,
  faEdit,
  faSave,
  faCancel,
  faUpload,
  faDownload,
  faFileAlt,
  faClipboard,
  faQuestionCircle,
  faExclamationTriangle,
  faCheckCircle,
  faTimesCircle,
  faInfoCircle as faInfo,
  faCarSide,
  faWrench,
  faSeedling,
  faShip,
  faCube,
  faTruckRampBox,
  faMotorcycle,
  faCog,
  faHandshake,
  faBuilding,
  faOilCan,
  faExclamationCircle,
  faUserTie,
  faFileContract,
  faUniversity,
  faCommentAlt,
  faPenFancy,
  faFileUpload,
  faFilePdf,
  faIdCard,
  faUserPlus,
  faKey,
  faBoxes,
  faCalendar,
  faCreditCard,
  faDollarSign,
  faServer,
  faCity,
  faFlag,
} from '@fortawesome/free-solid-svg-icons'

import {
  faGoogle,
  faApple,
  faFacebook,
  faTwitter,
  faInstagram,
  faLinkedin,
} from '@fortawesome/free-brands-svg-icons'

import App from './App.vue'
import router from './router'
import './assets/styles/main.css'
import { i18n } from '@/plugins/i18n'

// Add icons to library
library.add(
  faSearch,
  faShoppingCart,
  faHeart,
  faCog,
  faKey,
  faBoxes,
  faTachometerAlt,
  faSignOutAlt,
  faUser,
  faBars,
  faTimes,
  faHome,
  faShop,
  faInfoCircle,
  faUserPlus,
  faBlog,
  faCommentAlt,
  faPenFancy,
  faFileUpload,
  faFilePdf,
  faIdCard,
  faPhone,
  faBriefcase,
  faShieldAlt,
  faUndo,
  faHeadset,
  faHandshake,
  faBuilding,
  faOilCan,
  faExclamationCircle,
  faUserTie,
  faFileContract,
  faUniversity,
  faTruck,
  faDashboard,
  faBox,
  faBolt,
  faMapMarkerAlt,
  faSignOut,
  faEye,
  faEyeSlash,
  faPlus,
  faMinus,
  faTrash,
  faCheck,
  faArrowRight,
  faArrowLeft,
  faSpinner,
  faStar,
  faFilter,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faEnvelope,
  faLock,
  faUserCircle,
  faEdit,
  faSave,
  faCancel,
  faUpload,
  faDownload,
  faFileAlt,
  faClipboard,
  faQuestionCircle,
  faExclamationTriangle,
  faCheckCircle,
  faTimesCircle,
  faInfo,
  faGoogle,
  faApple,
  faFacebook,
  faTwitter,
  faInstagram,
  faLinkedin,
  faCarSide,
  faWrench,
  faSeedling,
  faShip,
  faCube,
  faTruckRampBox,
  faMotorcycle,
  faCalendar,
  faCreditCard,
  faDollarSign,
  faServer,
  faCity,
  faFlag
)

const app = createApp(App)

// Register FontAwesome component globally
app.component('font-awesome-icon', FontAwesomeIcon)

app.use(createPinia())
app.use(router)
app.use(i18n)
app.use(Toast, {
  position: 'top-right',
  timeout: 3000,
  closeOnClick: true,
  pauseOnFocusLoss: true,
  pauseOnHover: true,
  draggable: true,
  draggablePercent: 0.6,
  showCloseButtonOnHover: false,
  hideProgressBar: false,
  closeButton: 'button',
  icon: true,
  rtl: false,
})

app.use(VueLazyLoad, {
  // Optional: default placeholder (use public assets by absolute URL)
  loading: '/images/oil-droplet.gif',
  error: '/images/oil-droplet.jpg'
})

app.mount('#app')
