import { createApp } from 'vue'
import { createPinia } from 'pinia'
import App from './App.vue'
import router from './router'
import './assets/css/main.css'

// FontAwesome
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faHome,
  faUsers,
  faBox,
  faTruck,
  faShoppingCart,
  faFileText,
  faCog,
  faUser,
  faBars,
  faSearch,
  faBell,
  faSignOutAlt,
  faPlus,
  faEdit,
  faTrash,
  faEye,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faChevronUp,
  faCloudUpload,
  faTh,
  faList,
  faCogs,
  faTimesCircle,
  faSort,
  faChartLine,
  faChartBar,
  faPlusCircle,
  faUserPlus,
  faSortUp,
  faSortDown,
  faFilter,
  faDownload,
  faUpload,
  faSave,
  faCancel,
  faCheck,
  faTimes,
  faExclamationTriangle,
  faInfoCircle,
  faSpinner,
  faChartPie,
  faDollarSign,
  faCalendarAlt,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faGlobe,
  faLock,
  faUnlock,
  faKey,
  faShield,
  faDatabase,
  faServer,
  faCloud,
  faMobile,
  faDesktop,
  faTablet,
  faPrint,
  faShare,
  faHeart,
  faStar,
  faFlag,
  faTag,
  faBookmark,
  faComment,
  faLink,
  faSignInAlt,
  faEllipsisV,
  faArrowDown,
  faArrowUp,
  faArrowLeft,
  faArrowRight,
  faShieldAlt,
  faUserCheck,
  faUserTimes,
  faUserSecret,
  faUserLock,
  faUserSlash,
  faBolt,
  faUserClock,
  faClock,
  faCheckCircle,
  faQuestionCircle,
  faCopy,
  faBoxes,
  faImage,
  faMinus,
  faEquals,
  faTags,
  faPercentage,
} from '@fortawesome/free-solid-svg-icons'

// Add icons to library
library.add(
  faTags,
  faPercentage,
  faMinus,
  faEquals,
  faImage,
  faCopy,
  faBoxes,
  faUserLock,
  faUserSecret,
  faCheckCircle,
  faBolt,
  faClock,
  faUserClock,
  faQuestionCircle,
  faShieldAlt,
  faUserCheck,
  faUserTimes,
  faUserSlash,
  faArrowDown,
  faArrowUp,
  faArrowLeft,
  faArrowRight,
  faPlusCircle,
  faUserPlus,
  faSignInAlt,
  faEllipsisV,
  faHome,
  faUsers,
  faBox,
  faTruck,
  faShoppingCart,
  faFileText,
  faCog,
  faUser,
  faCloudUpload,
  faTh,
  faList,
  faCogs,
  faTimesCircle,
  faBars,
  faSearch,
  faBell,
  faSignOutAlt,
  faPlus,
  faEdit,
  faTrash,
  faEye,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faChevronUp,
  faSort,
  faSortUp,
  faSortDown,
  faFilter,
  faDownload,
  faUpload,
  faSave,
  faCancel,
  faCheck,
  faTimes,
  faExclamationTriangle,
  faInfoCircle,
  faSpinner,
  faChartLine,
  faChartBar,
  faChartPie,
  faDollarSign,
  faCalendarAlt,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faGlobe,
  faLock,
  faUnlock,
  faKey,
  faShield,
  faDatabase,
  faServer,
  faCloud,
  faMobile,
  faDesktop,
  faTablet,
  faPrint,
  faShare,
  faHeart,
  faStar,
  faFlag,
  faTag,
  faBookmark,
  faComment,
  faLink,
)

// Toast notifications
import Toast from 'vue-toastification'
import 'vue-toastification/dist/index.css'

const app = createApp(App)

// Use plugins
app.use(createPinia())
app.use(router)
app.use(Toast, {
  transition: 'Vue-Toastification__bounce',
  maxToasts: 20,
  newestOnTop: true,
  position: 'top-right',
  timeout: 5000,
  closeOnClick: true,
  pauseOnFocusLoss: true,
  pauseOnHover: true,
  draggable: true,
  draggablePercent: 0.6,
  showCloseButtonOnHover: false,
  hideProgressBar: false,
  closeButton: 'button',
  icon: true,
  rtl: false,
})

// Register global components
app.component('font-awesome-icon', FontAwesomeIcon)

app.mount('#app')
